name: Deploy to S3 (OIDC Role)

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::275023965558:role/Github_S3_FullAccess
          aws-region: ap-northeast-2

      - name: Sync to S3
        run: |
          aws s3 sync . s3://saas-275023965558-ap-northeast-2-an --delete
